#!/usr/bin/env python
import os

commands = []
commands.append("g++ -o ./sqlDatabase.o -c ./sqlDatabase.cpp")
commands.append("ar rc ./libsqlDatabase.a ./sqlDatabase.o")
commands.append("mv ./libsqlDatabase.a /usr/local/lib/libsqlDatabase.a")
commands.append("cp ./sqlDatabase.h /usr/include/mysql/sqlDatabase.h")
commands.append("rm sqlDatabase.o")

failed = False
for cmd in commands:
	ret = os.system(cmd)
	if( ret != 0 ):
		failed = True
		break

if( failed == True ):
	print "Installation failed."
else:
	print "Installation complete."
