var script22804 = function(self, actor, here, args, extra) {
	var ring = extra.obj;
	if( ring.vnum == 815 ) {
		wait 2;
		self.comm("nods and drops the ring into a pocket of her dress.");
		wait 3;
		self.say("I'll keep this safe with me until you return.");
		wait 5;
		self.say("When you step through the ter'angreal, you will no longer be in this world.");
		wait 3;
		here.echo("You feel a strange sensation from somewhere nearby.");
		wait 2;
		here.echo("An Aes Sedai steps forward and says 'Remember what must be remembered.'");
		wait 1;
		actor.send("Your skin tingles as a weave is cast over you.");
		act("$n shivers as a weave is cast over her.", false, actor, null, null, constants.TO_ROOM);
		wait 2;
		here.echo("A strange sensation from nearby gets weaker.");
		wait 4;
		self.say("But every scrape and cut you receive in that other world will be just as real as in ours.");
		wait 3;
		here.echo("You feel a strange sensation from somewhere nearby.");
		wait 2;
		here.echo("An Aes Sedai steps forward and says 'Remember what must be remembered.'");
		wait 1;
		actor.send("Your skin tingles as a weave is cast over you.");
		act("$n shivers as a weave is cast over her.", false, actor, null, null, constants.TO_ROOM);
		wait 2;
		here.echo("A strange sensation from nearby gets weaker.");
		wait 5;
		self.say("You will find a six-pointed star and stand on it, you will then be required to weave a certain weave to pass to the next test.");
		wait 4;
		self.say("Remember this order: air, fire, water, earth, spirit.");
		wait 5;
		self.say("That is the order in which you will be weaving.");
		wait 3;
		here.echo("You feel a strange sensation from somewhere nearby.");
		wait 2;
		here.echo("An Aes Sedai steps forward and says 'Remember what must be remembered.'");
		wait 1;
		actor.send("Your skin tingles as a weave is cast over you.");
		act("$n shivers as a weave is cast over her.", false, actor, null, null, constants.TO_ROOM);
		wait 2;
		here.echo("A strange sensation from nearby gets weaker.");
		wait 4;
		self.say("There will be distractions to keep you from your duties. Do not let this hinder you.");
		wait 3;
		here.echo("You feel a strange sensation from somewhere nearby.");
		wait 2;
		here.echo("An Aes Sedai steps forward and says 'Remember what must be remembered.'");
		wait 1;
		actor.send("Your skin tingles as a weave is cast over you.");
		act("$n shivers as a weave is cast over her.", false, actor, null, null, constants.TO_ROOM);
		wait 2;
		here.echo("A strange sensation from nearby gets weaker.");
		wait 4;
		self.say("Lastly, tell no one what has been said here today or of your journey through the ter'angreal.");
		wait 5;
		here.echo("You feel a strange sensation from somewhere nearby.");
		wait 3;
		actor.send("The Aes Sedai surrounding you begin weaving a unanimous pattern with their hands, channeling all Five Powers in to the ter'angreal.");
		act("The Aes Sedai around $n begin weaving their hands in a complicated pattern, channeling all Five Powers in to the ter'angreal.", false, actor, null, null, constants.TO_ROOM);
		wait 4;
		here.echo("The ter'angreal begins to revolve slowly and a portal of shimmering color can be seen through the center of the oval.");
		wait 5;
		self.say("Put your armor back on, " + actor.name + ". It is dangerous through the portal.");
		wait 1;
		actor.send("Type enter portal to continue to your first test.");
	}
}